# Generated by Django 4.2.4 on 2023-08-26 16:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('type_of_employee', models.CharField(choices=[('Supervisor', 'Supervisor'), ('Employee', 'Employee')], max_length=50)),
                ('addrress', models.CharField(max_length=250)),
                ('ssn', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999999999), django.core.validators.MinValueValidator(100000000)])),
                ('supervisor_code', models.IntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(9999), django.core.validators.MinValueValidator(1000)])),
                ('phno', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=8, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
