# Generated by Django 4.2.4 on 2023-08-27 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_alter_employee_ssn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='ssn',
            field=models.IntegerField(null=True),
        ),
    ]
