# Generated by Django 4.2.4 on 2023-08-27 09:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_alter_employee_ssn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phno',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='ssn',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(99999999), django.core.validators.MinValueValidator(10000000)]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='supervisor_code',
            field=models.IntegerField(blank=True, null=True, unique=True, validators=[django.core.validators.MaxValueValidator(9999), django.core.validators.MinValueValidator(1000)]),
        ),
    ]
