# Generated by Django 4.2.4 on 2023-08-29 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_alter_employee_phno_alter_employee_ssn_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_title', models.CharField(max_length=100)),
                ('room_type', models.CharField(max_length=100)),
                ('room_name', models.CharField(max_length=100)),
                ('room_floor', models.CharField(choices=[('1st Floor', '1st Floor'), ('2nd Floor', '2nd Floor'), ('3rd Floor', '3rd Floor')], max_length=50)),
                ('room_description', models.CharField(max_length=500)),
                ('price_per_night', models.IntegerField()),
                ('room_image', models.ImageField(upload_to='')),
            ],
        ),
    ]
