# Generated by Django 4.2.4 on 2023-08-29 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_rooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='room_type',
            field=models.CharField(choices=[('THE ROYAL', 'THE ROYAL'), ('THE GRAND', 'THE GRAND'), ('LUXURY SUITE', 'LUXURY SUITE')], max_length=100),
        ),
    ]
