# Generated by Django 4.2.4 on 2023-08-29 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_alter_rooms_room_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='room_image',
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='hotel.rooms')),
            ],
        ),
    ]
