# Generated by Django 4.2.4 on 2023-08-30 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0009_remove_rooms_room_image_roomimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='room_description',
            field=models.CharField(max_length=300),
        ),
    ]
