# Generated by Django 4.2.4 on 2023-09-01 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0012_reservation_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='no_of_adults',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)]),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='no_of_childrens',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2)]),
        ),
    ]
