# Generated by Django 4.2.4 on 2023-09-01 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0013_alter_reservation_no_of_adults_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='apt',
            field=models.IntegerField(),
        ),
    ]
