# Generated by Django 4.2.4 on 2023-09-01 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0014_alter_address_apt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='apt',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
