# Generated by Django 4.2.4 on 2023-09-01 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0015_alter_address_apt'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('room', 'check_in', 'check_out')},
        ),
    ]
