# Generated by Django 4.2.5 on 2023-09-23 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_employee_positions'),
        ('hotel', '0018_alter_reservation_reservation_number'),
    ]

    operations = [
    ]
